// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © zmwilliam

//Two EMAs, one slow and one fast
//  buy signal: when fast cross over slow
//  sell signal: when fast cross under slow

//Output
// plot both emas
// buy signal: color the candle with green
// sell signal: color the candle with red

//@version=4
study(title="EMA crossing indicator", shorttitle="EMA crossing", overlay=true)

in_ema_fast = input(defval=21, title="Fast EMA")
in_ema_slow = input(defval=50, title="Slow EMA")

val_ema_fast = ema(close, in_ema_fast)
val_ema_slow = ema(close, in_ema_slow)

buy_signal = crossover(val_ema_fast, val_ema_slow)
sell_signal = crossunder(val_ema_fast, val_ema_slow)

plot(val_ema_fast, title="Fast EMA", color=color.lime)
plot(val_ema_slow, title="Slow EMA", color=color.purple)

color_neutral = color.new(color.black, transp = 100)
color_bar = if buy_signal
    color.green
else if sell_signal
    color.red
else

    color_neutral
    
barcolor(color_bar)
